# syntax=docker/dockerfile:1

# Multi-stage build for the Land Explorer front-end: build the Vite/React SPA
# with Node+Yarn, then serve the static assets with Caddy.
# Modelled on mykomap-monolith/apps/front-end/Dockerfile, but WITHOUT the
# `reverse_proxy /api/*` block: the LX front-end talks to the back-end
# cross-origin (the API base URL is baked in via VITE_ROOT_URL at build time).
# See docs/coolify.md.

# Versions must be supplied. NODE_VERSION has no sane default - fail if unset.
ARG NODE_VERSION=nonesuch
ARG CADDY_VERSION=2.11

# ---- build stage ----
FROM node:${NODE_VERSION}-alpine AS build
WORKDIR /app
RUN apk add --no-cache git

COPY package.json yarn.lock ./
RUN --mount=type=cache,target=/usr/local/share/.cache/yarn yarn install --frozen-lockfile
COPY . .

# All client-side config is baked into the bundle at build time (Vite). Required
# values use ${VAR?} so the build fails loudly if they're missing; the two
# currently-unused vars are optional.
ARG VITE_ROOT_URL
ARG VITE_OS_KEY
ARG VITE_GEOCODER_TOKEN
ARG VITE_MAPBOX_TOKEN
ARG VITE_OS_PLACES_KEY
ARG VITE_PAYMENTS_URL
ARG VITE_USER_GUIDE_URL
ARG VITE_MIXPANEL_TOKEN
ARG VITE_MIXPANEL_PEPPER
ENV VITE_ROOT_URL=${VITE_ROOT_URL?} \
    VITE_OS_KEY=${VITE_OS_KEY?} \
    VITE_GEOCODER_TOKEN=${VITE_GEOCODER_TOKEN?} \
    VITE_MAPBOX_TOKEN=${VITE_MAPBOX_TOKEN?} \
    VITE_OS_PLACES_KEY=${VITE_OS_PLACES_KEY} \
    VITE_PAYMENTS_URL=${VITE_PAYMENTS_URL} \
    VITE_USER_GUIDE_URL=${VITE_USER_GUIDE_URL} \
    VITE_MIXPANEL_TOKEN=${VITE_MIXPANEL_TOKEN} \
    VITE_MIXPANEL_PEPPER=${VITE_MIXPANEL_PEPPER}
RUN yarn build

# ---- runtime stage ----
FROM caddy:${CADDY_VERSION}-alpine

# Caddy must know the hostname it should respond to; it's baked into the
# Caddyfile at build time (Caddy won't serve an unknown hostname).
ARG CADDY_HOSTNAME
ENV CADDY_HOSTNAME=${CADDY_HOSTNAME?}

WORKDIR /usr/share/caddy/
COPY --from=build /app/dist/ .

# Generate the Caddyfile into the image. Single-site shorthand (no braces).
# `try_files {path} /index.html` gives SPA fallback so client-side routes work.
# No HTTPS here: an external reverse proxy (Coolify/Apache) terminates TLS.
RUN <<SCRIPT
set -e
cat >/etc/caddy/Caddyfile <<EOF
# Autogenerated - see Dockerfile
${CADDY_HOSTNAME?}:80

root * /usr/share/caddy
encode gzip
try_files {path} /index.html
file_server
EOF
SCRIPT
