#!/bin/bash

buildTo=$1

if [ "$buildTo" == "staging" ] || [ "$buildTo" == "prod" ]; then
	echo 'Building land-map-app to' $buildTo
:
else
	echo 'deploy to staging or prod?'
	exit;
fi

rm -rf node_modules/*
npm install
npm run build prod
rm -rf build/service-worker.js

if [ "$buildTo" == "staging" ]; then
	echo 'Uploading to Staging'
	rsync -avz --delete -e 'ssh -i ~/.ssh/dev-build' build/ build@staging1.wearespork.net:/var/lib/tomcat8/webapps/landmapserver/ROOT/app/
fi

if [ "$buildTo" == "prod" ]; then
	echo 'Uploading to Server3'
	rsync -avz --delete -e 'ssh -i ~/.ssh/dev-build' build/ build@server3.wearespork.net:/var/lib/tomcat8/webapps/landmapserver/ROOT/app/
fi

echo 'Build Complete'
